conda-forge/nodejs-feedstock

recipe/meta.yaml

bump to 4.4.7

---

recipe/meta.yaml

added in alphabetical order
not sure if the build number needs to be bumped on this one.

add minrk to maintainers

---

appveyor.yml
ci_support/run_docker_build.sh
recipe/meta.yaml

and rerender with smithy 2.3.1

release 6.11.0

---

recipe/meta.yaml

10.x is LTS, so we should probably be keeping it up-to-date as well
closes #67

Package 10.15.3 on 10.x branch

---

recipe/meta.yaml

Update to 12.3.1 (fixes #82)

---

recipe/meta.yaml

Add blink1073 as maintainer

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
.ci_support/osx_.yaml
recipe/build.sh
recipe/linux-install.patch
recipe/meta.yaml

Build shared library

---

recipe/build.sh
recipe/meta.yaml

Update to 13.10.1

---

recipe/meta.yaml

nodejs 12.19.0

---

conda-forge.yml

See https://regro.github.io/cf-scripts/migrators.html#migrating-branches-on-your-feedstock
These older versions are still used in some places, so keep them uptodate with the most recent pinnings.

Support migrations on branches

---

recipe/meta.yaml

Checklist
Just updating to 14.15.1 manually.

nodejs v14.15.1

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
.ci_support/migrations/icu68.yaml
.scripts/run_docker_build.sh
recipe/conda_build_config.yaml
recipe/meta.yaml

Fix build to rerender again

---

.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
LICENSE.txt
README.md
recipe/meta.yaml

Add run_exports

---

recipe/meta.yaml

14.x: Add run_exports

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
.ci_support/migrations/icu68.yaml
.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
LICENSE.txt
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

12.x: Add run_exports

---

.azure-pipelines/azure-pipelines-linux.yml
.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
.travis.yml
LICENSE.txt
README.md
build-locally.py
recipe/meta.yaml

bump LTS to v14.17.1

---

recipe/meta.yaml

chore(meta): Upgrade node.js to 14.17.4

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-win.yml
.scripts/build_steps.sh
.scripts/logging_utils.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
.travis.yml
README.md
build-locally.py
recipe/meta.yaml

nodejs 12.22.6

---

recipe/meta.yaml

Fixes #211 
Fixes #215 
Checklist

nodejs v14.18.3

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
.ci_support/migrations/icu69.yaml
.ci_support/osx_64_.yaml
recipe/meta.yaml

14.x: icu69 migration

---

recipe/meta.yaml

nodejs v16.13.2

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/osx_64_openssl1.1.1.yaml
.ci_support/osx_64_openssl3.yaml
.ci_support/osx_arm64_openssl1.1.1.yaml
.ci_support/osx_arm64_openssl3.yaml
.circleci/config.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
LICENSE.txt
build-locally.py
recipe/meta.yaml

Update 16.x branch

---

recipe/meta.yaml

nodejs 16.16.0

---

recipe/meta.yaml

nodejs 16.17.0

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
.ci_support/osx_64_.yaml
.circleci/config.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
LICENSE.txt
build-locally.py
recipe/meta.yaml

nodejs 14.19.0

---

recipe/meta.yaml

nodejs 14.19.1

---

recipe/meta.yaml

nodejs 14.19.2

---

recipe/meta.yaml

nodejs 14.19.3

---

recipe/meta.yaml

nodejs 14.20.0

---

recipe/meta.yaml

nodejs 14.20.1

---

recipe/meta.yaml

updated to 18.12.1

---

recipe/meta.yaml

nodejs 18.14.0

---

recipe/meta.yaml

nodejs 18.14.1

---

recipe/meta.yaml

nodejs 18.14.2

---

recipe/meta.yaml

nodejs 18.15.0

---

recipe/meta.yaml

nodejs 16.19.0

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/migrations/icu72.yaml
.scripts/run_osx_build.sh
recipe/meta.yaml

nodejs 18.17.1

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/migrations/icu72.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.scripts/run_osx_build.sh
recipe/meta.yaml

nodejs 16.20.2

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
README.md
recipe/meta.yaml

nodejs 20.9.0

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/migrations/icu73.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.ci_support/win_64_.yaml
.gitignore
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
azure-pipelines.yml
build-locally.py
recipe/meta.yaml

Rebuild nodejs to get libuv 1.48.

---

recipe/meta.yaml

nodejs 22.4.0

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
azure-pipelines.yml
recipe/build.sh
recipe/meta.yaml

nodejs 20.18.0

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_nodejs20.yaml
.ci_support/linux_64_nodejs22.yaml
.ci_support/linux_aarch64_nodejs20.yaml
.ci_support/linux_aarch64_nodejs22.yaml
.ci_support/osx_64_nodejs20.yaml
.ci_support/osx_64_nodejs22.yaml
.ci_support/osx_arm64_nodejs20.yaml
.ci_support/osx_arm64_nodejs22.yaml
.ci_support/win_64_nodejs20.yaml
.ci_support/win_64_nodejs22.yaml
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
README.md
build-locally.py
recipe/meta.yaml

nodejs 20.18.1

---

recipe/meta.yaml

nodejs 22.13.0

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
conda-forge.yml
recipe/conda_build_config.yaml
recipe/meta.yaml

nodejs v24.3.0

---

.azure-pipelines/azure-pipelines-osx.yml
recipe/meta.yaml

nodejs v20.19.5

---

.azure-pipelines/azure-pipelines-osx.yml
.github/workflows/conda-build.yml
pixi.toml
recipe/recipe.yaml

nodejs v22.19.0
